### PR TITLE
Mac's Current PR

### PR DESCRIPTION
**Pull request by Mac898**
My first PR to this repository. Let me know how I'm going, please :)

### CODE REVIEW

**Comment by DarkenMoon97** [comment]
He won't care as long as those link back to the original file(s).

**Comment by Mac898** [comment]
The owner of the mods Reika says that not using the adfly links is not something he is going to allow, So i am forced to use the adf.ly links

**Comment by Mac898** [comment]
Even thats pushing it too. View:
https://sites.google.com/site/reikasminecraft/licensing

3. REDISTRIBUTION
These mods may not be uploaded or mirrored by anyone other than the owner, and all links to these mods must link to this page, not directly to adfly, MediaFire, or Curse. Any unauthorized links to the mods that bypass this forum page will be discovered and forced to be deleted.

**Comment by Forkk** [comment]
I'll try and merge this as is, but in the future please make a separate branch and pull request for each mod.

Adfly links are perfectly fine. We do the same for redpower and other mods with adfly links.

**Comment by Mac898** [comment]
Ok thanks forkk.

**Pull request closed without merging**
