### PR TITLE
Add Forge 1.0.7 for b1.7.3

### PR DESCRIPTION
**Pull request by Scotsguy**
Files by @CindyLouWho03

### CODE REVIEW

**Comment by peterix** [comment]
```
yaml.parser.ParserError: while parsing a block mapping
  in "mods/minecraftforge.yaml", line 1590, column 3
expected <block end>, but found '<block mapping start>'
  in "mods/minecraftforge.yaml", line 1613, column 5
```

**Comment by peterix** [comment]
In general, this has whitespace issues and looks like it's missing a `-`.

**Comment by asiekierka** [comment]
https://sourceforge.net/projects/buildcraft/files/Forge%201.0.7%2020110907/

There's also this build; not sure if it's any different

**Comment by Scotsguy** [comment]
Those have the same checksum, so no they're not different

**Pull request closed without merging**
